# Where to save the checkpoints
encoder_type: brnn
word_vec_size: 512
rnn_size: 512

eval:
  scorers: bleu
  export_on_best: bleu


copy_attn: true
global_attention: mlp
layers: 1
dropout: 0.5

# Optimization
model_dtype: "fp32"
optim: "adam"
learning_rate: 2
warmup_steps: 6000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

