# Where to save the checkpoints
encoder_type: brnn
share_decoder_embeddings: true
share_embeddings: true
word_vec_size: 300
rnn_size: 300

eval:
  scorers: bleu
  export_on_best: bleu

max_length: 50
copy_attn: true
global_attention: mlp
layers: 2
max_grad_norm: 2
dropout: 0.5

optim: adam
learning_rate: 0.0005
reuse_copy_attn: true
copy_loss_by_seqlength: true
bridge: true
seed: 777
world_size: 1

