save_data: datasets/nat-str/samples
src_vocab: datasets/nat-str/vocab/portuguese.vocab
tgt_vocab: datasets/nat-str/vocab/portuguese.vocab
overwrite: False
share_vocab: True
data:
 corpus_1:
   path_src: datasets/nat-str/train.nat
   path_tgt: datasets/nat-str/train.str
 valid:
   path_src: datasets/nat-str/val.nat
   path_tgt: datasets/nat-str/val.str
save_model: transformer/run/nat-str/model
# Where to save the checkpoints
encoder_type: transformer
decoder_type: transformer
enc_layers: 6
dec_layers: 6
heads: 6
transformer_ff: 2048
dropout_steps: [0]
attention_dropout: [0.1]
share_decoder_embeddings: true
share_embeddings: true
word_vec_size: 300
rnn_size: 300

copy_attn: true
global_attention: mlp
layers: 1
max_grad_norm: 2
dropout: 0.5

optim: adam
learning_rate: 0.0005
reuse_copy_attn: true
copy_loss_by_seqlength: true
bridge: true
seed: 777
world_size: 1
max_length: 50
eval:
  scorers: bleu
  export_on_best: bleu

save_checkpoint_steps: 3000
train_steps: 3000
batch_size: 32
valid_batch_size: 32